name: Testing

on:
  push:
    branches:
      - "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/testing.yml"
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/testing.yml"

permissions:
  contents: read

jobs:
  testing:
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [ "1.20", "1.21", "1.22", "1.23" ]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit
          disable-telemetry: true

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run test without Tor
        run: |
          make test
          make test-cover

      - name: Set up Tor
        uses: tor-actions/setup-tor@64121bc84235ab7038224e8ce08601efdb9bd8d9

      - name: Run test with Tor standalone
        run: |
          make test
          make test-cover

      - name: Set up Tor
        uses: tor-actions/setup-tor@64121bc84235ab7038224e8ce08601efdb9bd8d9
        with:
          daemon: true
          port: 9050

      - name: Run test with Tor daemon
        run: |
          make test
          make test-cover

      - name: Upload coverage
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: coverage-${{ matrix.os }}-${{ matrix.go }}
          path: coverage.*

      - name: Run integration test
        run: make test-integration
